=== duchien85/springapps/hr-base/hr-model/src/test/resources/xml/hr-model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="hr-model"
  xmlns="hr-model"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  <xs:element name="employee" type="employeeType"/>
  <xs:element name="employees" type="employeesType" />

  <xs:element name="job" type="jobType"/>
  <xs:element name="jobs" type="jobsType"/>

  <xs:element name="jobHistory" type="jobHistoryType"/>
  <xs:element name="jobHistories" type="jobHistoriesType"/>

  <xs:element name="department" type="departmentType"/>
  <xs:element name="departments" type="departmentsType"/>

  <xs:element name="location" type="locationType"/>

  <xs:element name="country" type="countryType"/>
  <xs:element name="countries" type="countriesType"/>

  <xs:element name="region" type="regionType"/>
  <xs:element name="regions" type="regionsType"/>

  <xs:complexType name="employeeType" >
    <xs:sequence>
      <xs:element name="first_name" type="xs:string" nillable="true"/>
      <xs:element name="last_name" type="xs:string" />
      <xs:element name="email" type="xs:string" />
      <xs:element name="phone_number" type="xs:string" nillable="true"/>
      <xs:element name="hire_date" type="xs:date"/>
      <xs:element name="jobId" type="xs:string"/>
      <xs:element name="salary" type="xs:positiveInteger" nillable="true"/>
      <xs:element name="commission_pct" type="xs:decimal" nillable="true"/>
      <xs:element name="managerId" type="xs:positiveInteger" nillable="true" />
      <xs:element name="departmentId" type="xs:positiveInteger" nillable="true"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" />
  </xs:complexType>

  <xs:complexType name="employeesType">
    <xs:sequence>
      <xs:element name="employee" type="employeeType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="jobType" >
    <xs:sequence>
      <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="min_salary" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
      <xs:element name="max_salary" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>

  <xs:simpleType name="employeeIdType">
    <xs:restriction base="xs:positiveInteger">
      
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="jobsType">
    <xs:sequence>
      <xs:element name="job" type="jobType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="jobHistoryType" >
    <xs:sequence>
      <xs:element name="employeeId" type="xs:positiveInteger" />
      <xs:element name="start_date" type="xs:date"/>
      <xs:element name="end_date" type="xs:date" />
      <xs:element name="jobId" type="xs:string" />      
      <xs:element name="departmentId" type="xs:positiveInteger" nillable="true"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="jobHistoriesType">
    <xs:sequence>
      <xs:element name="jobHistory" type="jobHistoryType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="departmentType" >
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="managerId" type="xs:positiveInteger" nillable="true"/>
      <xs:element name="locationId" type="xs:positiveInteger" nillable="true"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="departmentsType">
    <xs:sequence>
      <xs:element name="department" type="departmentType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="locationType">
    <xs:sequence>
      <xs:element name="street_address" type="xs:string" nillable="true"/>
      <xs:element name="postal_code" type="xs:string" nillable="true"/>
      <xs:element name="city" type="xs:string" />
      <xs:element name="state_province" type="xs:string" nillable="true"/>
      <xs:element name="countryId" type="xs:string" nillable="true"/>        
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" />
  </xs:complexType>

  <xs:complexType name="countryType">
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element name="regionId" type="xs:positiveInteger" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="countriesType">
    <xs:sequence>
      <xs:element name="country" type="countryType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="regionType" >
    <xs:sequence>    
      <xs:element name="name" type="xs:string" nillable="true"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" />
  </xs:complexType>

  <xs:complexType name="regionsType">
    <xs:sequence>
      <xs:element name="region" type="regionType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== duchien85/springapps/hr-base/hr-model/src/test/resources/xml/employee.xml
<?xml version="1.0" encoding="UTF-8" ?>
<employee id="100"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="hr-model" 
  xsi:schemaLocation="hr-model hr-model.xsd">
  <first_name>Steven</first_name>
  <last_name>King</last_name>
  <email>SKING</email>
  <phone_number>515.123.4567</phone_number>
  <hire_date>1987-06-17</hire_date>
  <jobId>AD_PRES</jobId>
  <salary>24000</salary>
  <commission_pct xsi:nil="true" />
  <managerId xsi:nil="true" />
  <departmentId>90</departmentId>
</employee>

=== duchien85/springapps/hr-base/hr-model/src/test/resources/xml/departmentList.xml
<?xml version="1.0" encoding="UTF-8" ?>
<departments
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="hr-model" 
  xsi:schemaLocation="hr-model hr-model.xsd">
  <department id="10">
    <name>Administration</name>
    <managerId>200</managerId>
    <locationId>1700</locationId>
  </department>
  <department id="20">
    <name>Marketing</name>
    <managerId>201</managerId>
    <locationId>1800</locationId>
  </department>
  <department id="30">
    <name>Purchasing</name>
    <managerId>114</managerId>
    <locationId>1700</locationId>
  </department>
  <department id="40">
    <name>Human Resources</name>
    <managerId>203</managerId>
    <locationId>2400</locationId>
  </department>
</departments>

=== duchien85/springapps/hr-base/hr-model/src/test/resources/xml/jobs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<jobs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hr-model.xsd">
  <job id="AD_PRES">
    <title>President</title>
    <min_salary>20000</min_salary>
    <max_salary>40000</max_salary>
  </job>
  <job id="AD_VP">
    <title>Administration Vice President</title>
    <min_salary>15000</min_salary>
    <max_salary>30000</max_salary>
  </job>
  <job id="AD_ASST">
    <title>Administration Assistant</title>
    <min_salary>3000</min_salary>
    <max_salary>6000</max_salary>
  </job>
  <job id="FI_MGR">
    <title>Finance Manager</title>
    <min_salary>8200</min_salary>
    <max_salary>16000</max_salary>
  </job>
</jobs>

=== duchien85/springapps/hr-base/hr-model/src/test/resources/xml/jobHistories.xml
<?xml version="1.0" encoding="UTF-8" ?>
<jobHistories
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="hr-model" 
  xsi:schemaLocation="hr-model hr-model.xsd">	  
    <jobHistory>
      <employeeId>101</employeeId>
      <start_date>1989-09-21</start_date>
      <end_date>1993-10-27</end_date>
      <jobId>AC_ACCOUNT</jobId>
      <departmentId>110</departmentId>
    </jobHistory>
    <jobHistory>
      <employeeId>101</employeeId>
      <start_date>1993-10-28</start_date>
      <end_date>1997-03-15</end_date>
      <jobId>AC_MGR</jobId>
      <departmentId>110</departmentId>
    </jobHistory>
</jobHistories>

=== duchien85/springapps/hr-base/hr-model/src/test/resources/xml/countryList.xml
<?xml version="1.0" encoding="UTF-8"?>
<countries
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="hr-model" 
  xsi:schemaLocation="hr-model hr-model.xsd">
  <country id="AR">
    <name>Argentina</name>
    <regionId>2</regionId>
  </country>
  <country id="AU">
    <name>Australia</name>
    <regionId>3</regionId>
  </country>
  <country id="BE">
    <name>Belgium</name>
    <regionId>1</regionId>
  </country>
</countries>
